alpha: 
  - 0.01
  - 0.10
automatic_entropy_tuning: false
batch_size: 256
cores: 2
cuda: 0
env_name: Reacher-v4
eval: true
exp_id: reacher
gamma: 0.99
hidden_size: 256
lr: 0.0003
num_steps: 250000
policy: Gaussian
replay_size: 1000000
seed: 2022
start_steps: 10000
target_update_interval: 1
tau: 0.005
updates_per_step: 1
test_step: 1000
qtog: 1
gtoq: 1000
tau_g: 0.005
teian: True
