alpha: 0.05
automatic_entropy_tuning: false
batch_size: 256
cores: 2
cuda: 0
env_name: Humanoid-v4
eval: true
exp_id: humanoid
gamma: 0.99
hidden_size: 256
lr: 0.0003
num_steps: 50000
policy: Gaussian
replay_size: 1000000
max_episode_steps: 1000000
seed: 2021
start_steps: 10000
target_update_interval: 1
tau: 0.005
updates_per_step: 1
